In [ ]:
import numpy as np
import ehrapy as ep

adata = ep.dt.mimic_2(encoded=False)
adata.X[0][11] = np.nan
adata.X[0][11]

_ = ep.pp.qc_metrics(adata)


Installed version 0.3.0 of ehrapy is newer than the latest release 0.2.0! You are running a nightly version and 
features may break!

TypeError! Setting quality control metrics to nan. Did you encode your data?

In [10]:
from ehrapy.io._read import read_csv
from ehrapy.preprocessing._encode import encode
from ehrapy.preprocessing._quality_control import _obs_qc_metrics, _var_qc_metrics
import numpy as np
def test_obs_nan_qc_metrics():
    adata = read_csv(dataset_path="/Users/xinyuezhang/ehrapy/tests/preprocessing/test_data_encode/dataset1.csv")
    adata.X[0][4] = np.nan
    adata2 = encode(adata, encodings={"one_hot_encoding": ["clinic_day"]})
    obs_metrics = _obs_qc_metrics(adata2)
    assert obs_metrics.iloc[0][0] == 1



Output()

/Users/xinyuezhang/ehrapy/ehrapy/preprocessing/_encode.py:324: FutureWarning: X.dtype being converted to np.float32 from object. In the next version of anndata (0.9) conversion will not be automatic. Pass dtype explicitly to avoid this warning. Pass `AnnData(X, dtype=X.dtype, ...)` to get the future behavour.
  encoded_ann_data = AnnData(


In [15]:
from ehrapy.io._read import read_csv
from ehrapy.preprocessing._encode import encode
from ehrapy.preprocessing._quality_control import _obs_qc_metrics, _var_qc_metrics
import numpy as np
def test_var_nan_qc_metrics():
    adata = read_csv(dataset_path="/Users/xinyuezhang/ehrapy/tests/preprocessing/test_data_encode/dataset1.csv")
    adata.X[0][4] = np.nan
    adata2 = encode(adata, encodings={"one_hot_encoding": ["clinic_day"]})
    var_metrics = _var_qc_metrics(adata2)
    assert var_metrics.iloc[0][0] == 1
    assert var_metrics.iloc[1][0] == 1
    assert var_metrics.iloc[2][0] == 1
    assert var_metrics.iloc[3][0] == 1
    assert var_metrics.iloc[4][0] == 1



In [12]:
var_metrics

missing_values_abs  missing_values_pct  mean  \
ehrapycat_clinic_day_Friday                     1                20.0   NaN   
ehrapycat_clinic_day_Monday                     1                20.0   NaN   
ehrapycat_clinic_day_Saturday                   1                20.0   NaN   
ehrapycat_clinic_day_Sunday                     1                20.0   NaN   
ehrapycat_clinic_day_nan                        1                20.0   NaN   
patient_id                                      0                 0.0   NaN   
los_days                                        0                 0.0   NaN   
b12_values                                      0                 0.0   NaN   
survival                                        0                 0.0   NaN   

                               median  standard_deviation  min  max  
ehrapycat_clinic_day_Friday       NaN                 NaN  NaN  NaN  
ehrapycat_clinic_day_Monday       NaN                 NaN  NaN  NaN  
ehrapycat_clinic_day_Saturday     NaN                 NaN  NaN  NaN  
ehrapycat_clinic_day_Sunday       NaN                 NaN  NaN  NaN  
ehrapycat_clinic_day_nan          NaN                 NaN  NaN  NaN  
patient_id                        NaN                 NaN  NaN  NaN  
los_days                          NaN                 NaN  NaN  NaN  
b12_values                        NaN                 NaN  NaN  NaN  
survival                          NaN                 NaN  NaN  NaN

In [13]:
assert var_metrics.iloc[0][0] == 1

In [1]:
from ehrapy.io._read import read_csv
import numpy as np
import ehrapy
from ehrapy.preprocessing._encode import DuplicateColumnEncodingError, _reorder_encodings, encode
adata = read_csv(dataset_path="/Users/xinyuezhang/ehrapy/tests/preprocessing/test_data_encode/dataset1.csv")


Installed version 0.3.0 of ehrapy is newer than the latest release 0.2.0! You are running a nightly version and 
features may break!

2022-12-02 16:39:01,621 - root INFO - Added all columns to `obs`.
2022-12-02 16:39:01,626 - root INFO - Transformed passed dataframe into an AnnData object with n_obs x n_vars = `5` x `5`.


In [2]:
adata.X[0][4] = np.nan

In [3]:
adata2 = encode(adata, encodings={"one_hot_encoding": ["clinic_day"]})

2022-12-02 16:39:05,772 - root INFO - The original categorical values `['clinic_day']` were added to uns.


Output()

2022-12-02 16:39:05,801 - root INFO - Updated the original layer after encoding.
2022-12-02 16:39:05,807 - root INFO - Added `['clinic_day']` columns to `X`.
2022-12-02 16:39:05,813 - root INFO - The original categorical values `['clinic_day']` were added to obs.


/Users/xinyuezhang/ehrapy/ehrapy/preprocessing/_encode.py:333: FutureWarning: X.dtype being converted to np.float32 from object. In the next version of anndata (0.9) conversion will not be automatic. Pass dtype explicitly to avoid this warning. Pass `AnnData(X, dtype=X.dtype, ...)` to get the future behavour.
  encoded_ann_data = AnnData(


In [4]:
adata.X

array([[12, 14, 500, False, nan],
       [13, 7, 330, False, 'Saturday'],
       [14, 10, 800, True, 'Monday'],
       [15, 11, 765, True, 'Sunday'],
       [16, 3, 800, True, 'Friday']], dtype=object)

In [5]:
adata2.X

array([[  0.,   0.,   0.,   0.,   1.,  12.,  14., 500.,   0.],
       [  0.,   0.,   1.,   0.,   0.,  13.,   7., 330.,   0.],
       [  0.,   1.,   0.,   0.,   0.,  14.,  10., 800.,   1.],
       [  0.,   0.,   0.,   1.,   0.,  15.,  11., 765.,   1.],
       [  1.,   0.,   0.,   0.,   0.,  16.,   3., 800.,   1.]],
      dtype=float32)

In [6]:
_ = ehrapy.pp.qc_metrics(adata2)

2022-12-02 16:39:15,341 - root INFO - Added the calculated metrics to AnnData's `obs` and `var`.


In [7]:
adata2.obs

clinic_day  missing_values_abs  missing_values_pct
0        NaN                   0                 0.0
1   Saturday                   0                 0.0
2     Monday                   0                 0.0
3     Sunday                   0                 0.0
4     Friday                   0                 0.0

In [24]:
_ = ehrapy.pp.qc_metrics(adata)

TypeError! Setting quality control metrics to nan. Did you encode your data?

In [25]:
adata.obs

missing_values_abs  missing_values_pct
0                   1                20.0
1                   0                 0.0
2                   0                 0.0
3                   0                 0.0
4                   0                 0.0

In [3]:
encoded_ann_data

AnnData object with n_obs × n_vars = 5 × 5
    obs: 'survival', 'clinic_day'
    uns: 'numerical_columns', 'non_numerical_columns', 'original_values_categoricals', 'var_to_encoding', 'encoding_to_var'
    layers: 'original'

In [4]:
adata

AnnData object with n_obs × n_vars = 5 × 5
    uns: 'numerical_columns', 'non_numerical_columns'
    layers: 'original'

In [6]:
adata.X[0][4] = np.nan

In [7]:
adata.X

array([[12, 14, 500, False, nan],
       [13, 7, 330, False, 'Saturday'],
       [14, 10, 800, True, 'Monday'],
       [15, 11, 765, True, 'Sunday'],
       [16, 3, 800, True, 'Friday']], dtype=object)

In [4]:
adata = ep.dt.mimic_2(encoded=False)

In [5]:
adata


AnnData object with n_obs × n_vars = 1776 × 46
    uns: 'numerical_columns', 'non_numerical_columns'
    layers: 'original'

In [13]:
adata.uns

OverloadedDict, wrapping:
	OrderedDict([('numerical_columns', ['bun_first', 'hgb_first', 'temp_1st', 'abg_count', 'sapsi_first', 'sepsis_flg', 'creatinine_first', 'icu_los_day', 'tco2_first', 'sodium_first', 'wbc_first', 'mort_day_censored', 'iv_day_1', 'weight_first', 'potassium_first', 'day_icu_intime_num', 'bmi', 'age', 'platelet_first', 'po2_first', 'chloride_first', 'map_1st', 'pco2_first', 'hospital_los_day', 'hour_icu_intime', 'spo2_1st', 'hr_1st', 'sofa_first']), ('non_numerical_columns', ['icu_exp_flg', 'resp_flg', 'censor_flg', 'gender_num', 'liver_flg', 'afib_flg', 'service_unit', 'mal_flg', 'chf_flg', 'service_num', 'cad_flg', 'renal_flg', 'day_28_flg', 'hosp_exp_flg', 'day_icu_intime', 'stroke_flg', 'copd_flg', 'aline_flg'])])
With overloaded keys:
	['neighbors'].

In [15]:
from anndata import AnnData
import pandas as pd


obs_data = {
            "disease": ["cancer", "tumor"],
            "country": ["Germany", "switzerland"],
            "sex": ["male", "female"],
        }
var_data = {
    "alive": ["yes", "no", "maybe"],
    "hospital": ["hospital 1", "hospital 2", "hospital 1", "hospital 2", "hospital 2"],
    "crazy": ["yes", "yes", "yes"],
}
adata = AnnData(
            X=np.array([[0.21, np.nan, 41.42], [np.nan, np.nan, 7.234], [0.21, np.nan, 41.42], [np.nan, np.nan, 7.234], [0.21, np.nan, 41.42]], dtype=np.float32),
            obs=pd.DataFrame(data=obs_data),
            var=pd.DataFrame(data=var_data, index=["Acetaminophen", "hospital", "crazy"]),
        )

/Users/xinyuezhang/ehrapy/.venv/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)


In [16]:
adata.obs

disease      country     sex
0  cancer      Germany    male
1   tumor  switzerland  female
2  cancer      Germany    male
3  cancer      Germany  female
4  cancer          NaN    male

In [17]:
adata.var

alive    hospital crazy
Acetaminophen    yes  hospital 1   yes
hospital          no  hospital 2   yes
crazy          maybe  hospital 1   yes

In [21]:
adata

AnnData object with n_obs × n_vars = 5 × 3
    obs: 'disease', 'country', 'sex'
    var: 'alive', 'hospital', 'crazy'
    layers: 'original'

In [18]:
adata.X

array([[ 0.21 ,    nan, 41.42 ],
       [   nan,    nan,  7.234],
       [ 0.21 ,    nan, 41.42 ],
       [   nan,    nan,  7.234],
       [ 0.21 ,    nan, 41.42 ]], dtype=float32)

In [3]:
print(adata.obs.iloc[0])

missing_values_abs    1.000000
missing_values_pct    2.173913
Name: 0, dtype: float64


In [2]:
print(adata.var.iloc[11])

missing_values_abs    1.000000
missing_values_pct    0.056306
mean                       NaN
median                     NaN
standard_deviation         NaN
min                        NaN
max                        NaN
Name: day_icu_intime, dtype: float64


In [4]:
adata2 = ep.pp.encode(adata, encodings={"one_hot_encoding": ["service_unit", "day_icu_intime"]})

Output()

/Users/xinyuezhang/ehrapy/ehrapy/preprocessing/_encode.py:324: FutureWarning: X.dtype being converted to np.float32 from object. In the next version of anndata (0.9) conversion will not be automatic. Pass dtype explicitly to avoid this warning. Pass `AnnData(X, dtype=X.dtype, ...)` to get the future behavour.
  encoded_ann_data = AnnData(


In [5]:
_ = ep.pp.qc_metrics(adata2)
print(adata2.obs.iloc[0])

TypeError! Setting quality control metrics to nan. Did you encode your data?

missing_values_abs           1
missing_values_pct    1.818182
service_unit              SICU
day_icu_intime             NaN
Name: 0, dtype: object


In [9]:
adata2.var

missing_values_abs  missing_values_pct  \
ehrapycat_service_unit_FICU                          0            0.000000   
ehrapycat_service_unit_MICU                          0            0.000000   
ehrapycat_service_unit_SICU                          0            0.000000   
ehrapycat_day_icu_intime_Friday                      1            0.056306   
ehrapycat_day_icu_intime_Monday                      1            0.056306   
ehrapycat_day_icu_intime_Saturday                    1            0.056306   
ehrapycat_day_icu_intime_Sunday                      1            0.056306   
ehrapycat_day_icu_intime_Thursday                    1            0.056306   
ehrapycat_day_icu_intime_Tuesday                     1            0.056306   
ehrapycat_day_icu_intime_Wednesday                   1            0.056306   
ehrapycat_day_icu_intime_nan                         1            0.056306   
aline_flg                                            0            0.000000   
icu_los_day                                          0            0.000000   
hospital_los_day                                     0            0.000000   
age                                                  0            0.000000   
gender_num                                           1            0.056306   
weight_first                                       110            6.193694   
bmi                                                466           26.238739   
sapsi_first                                         85            4.786036   
sofa_first                                           6            0.337838   
service_num                                          0            0.000000   
day_icu_intime_num                                   1            0.056306   
hour_icu_intime                                      0            0.000000   
hosp_exp_flg                                         0            0.000000   
icu_exp_flg                                          0            0.000000   
day_28_flg                                           0            0.000000   
mort_day_censored                                    0            0.000000   
censor_flg                                           0            0.000000   
sepsis_flg                                           0            0.000000   
chf_flg                                              0            0.000000   
afib_flg                                             0            0.000000   
renal_flg                                            0            0.000000   
liver_flg                                            0            0.000000   
copd_flg                                             0            0.000000   
cad_flg                                              0            0.000000   
stroke_flg                                           0            0.000000   
mal_flg                                              0            0.000000   
resp_flg                                             0            0.000000   
map_1st                                              0            0.000000   
hr_1st                                               0            0.000000   
temp_1st                                             3            0.168919   
spo2_1st                                             0            0.000000   
abg_count                                            0            0.000000   
wbc_first                                            8            0.450450   
hgb_first                                            8            0.450450   
platelet_first                                       8            0.450450   
sodium_first                                         5            0.281532   
potassium_first                                      5            0.281532   
tco2_first                                           5            0.281532   
chloride_first                                       5            0.281532   
bun_first                                            5    